### ISSUE TITLE
Infinite resource showing "attempt to compare number with nil" error

### ISSUE THREAD

**Issue by fredso104** [gqxastg/ACNH-Cheat-Tables#13]
As the title says whenever I try to toggle this cheat on, the lua engine pop up shows continuous errors of "attempt to compare number with nil" - I saw you said in another issue that you could try changing the 98 value to something like 29 but this still gives me the same issue

**Comment by gqxastg** [comment]
```
  if ( cht04 or cht02 ) then
    for i = 1,120 do
      local s = readBytes( 'items+18+90*'..string.format('%x',i-1), 1 )
      if s > 0 and s < 255 then
        writeBytes( 'items+18+90*'..string.format('%x',i-1), 200 )
      end
    end
  end
```
Just remove these contents from the script. (also apply the change I mentioned in another issue)
The root cause is that currently "Infinite Base Resources" will also enable "Increased Stack Sizes", and the latter is broken.
I will try fundamentally solving this problem later.

**Comment by fredso104** [comment]
Thanks! I did this and while I don't get that error anymore, it doesn't look like the cheat works in-game (e.g. when crafting, I still went down from 25 to 20 hardwood) - no worries, I can wait until you try solve that problem that you said :)
