### ISSUE TITLE
Error:heap already exists

### ISSUE THREAD

**Issue by xXcarlos117Xx2** [gqxastg/ACNH-Cheat-Tables#9]
Everytime i just click the "<- ENABLE AFTER LOADING GAME" just pops up this error.
Doesn't load the table correctly.
Yuzu 1421 updated 05/05/2023
AC:NH 2.0.6
![image](https://user-images.githubusercontent.com/19764055/236521871-82303122-c0c9-44ab-a95b-0583abb3151e.png)

**Comment by gqxastg** [comment]
https://fearlessrevolution.com/viewtopic.php?t=18846
`One thing to keep in mind is that with CE versions prior to 7.3, the lua "registerSymbol" will throw an error if the symbol already exists.`

It's about a issue with code logic between different versions of Cheat Engine.
So far, you can only use it on CE **7.3** or **7.4**, considering there are other issues with the current 7.5 version.

Alternatively, you can consider editing the script of `<- ENABLE AFTER LOADING GAME` temporarily.
Just insert a new line `unregisterSymbol('heap')` before **line 65** and **88**. (original line number)

I will include this in the next update, but overall, I still recommend using the new version of CE.
